services:
  backend:
    build: ./Server
    ports:
      - "8080:8080"
    environment:
      - DB_url=${DB_url}
      - DB_user=${DB_user}
      - DB_password=${DB_password}
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
    env_file:
      - .env

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend